### ISSUE TITLE
Não Utilizar react-scripts

### ISSUE THREAD

**Issue by llmdev** [viniarruda/spotify-project#4]
Opa ae Vinicius beleza ? Aqui é o Lucas Lopes da XPI, seria possível vc substituir o react-scripts e configurar webpack babel na mão ?

Abrass

**Comment by viniarruda** [comment]
Fala Lucas, beleza! Hoje a noite chegando em casa faço essa alteração. Valeu!

**Comment by viniarruda** [comment]
@llmdev Fiz uma alteração incluindo o webpack na branch `webpack` , porém cheguei a um impasse. Tive que fazer várias alterações e instalações de packages, mas o bundle não está conseguindo ler da raiz por conta do router, então vi que o pessoal usou pra corrigir o `html-webpack-plugin`, mas quando importo ele no webpack.config acaba quebrando toda minha estrutura por conta dos hooks. 

Se souber como corrigir isso e puder me ajudar nisso. Pelas issues do react, parece que há incompatibilidade dos hooks com algumas coisas, inclusive com o hot-loader.

**Comment by llmdev** [comment]
Opa, vou ver se consigo te ajudar no final de semana.

**Comment by viniarruda** [comment]
Resolvido na branch `webpack`
